// Números (ids) que tenían los productos hasta el 30/09/2026, cuando la canasta y las listas
// se guardaban por número. Sirve solo para convertir lo que quedó guardado en el navegador
// (ver migrar en canasta.ts): esos números cambian cada vez que se arma la base de cero, los
// nombres no.
export const NOMBRES_VERSION_1: Record<number, string> = {
  3: "Aceite de girasol",
  4: "Aceite de maíz",
  5: "Aceite de soja",
  7: "Afeitadora",
  8: "Agua con gas",
  9: "Agua en bidón",
  11: "Agua sin gas",
  12: "Aguja vacuna",
  13: "Alcohol",
  14: "Alcohol en gel",
  15: "Algodón",
  17: "Arroz blanco",
  18: "Arvejas en conserva",
  20: "Azúcar",
  21: "Banana",
  27: "Café molido",
  28: "Carne picada",
  32: "Cerveza",
  33: "Champú",
  36: "Chorizos",
  37: "Cinta adhesiva",
  39: "Cocoa",
  41: "Colonia y talco",
  45: "Crema facial",
  46: "Curitas",
  47: "Desodorante en aerosol",
  48: "Detergente para vajilla",
  49: "Dulce de leche",
  50: "Dulce de membrillo",
  53: "Fideos al huevo",
  54: "Fideos semolados",
  55: "Frankfurters",
  57: "Galletitas al agua",
  58: "Gasa estéril",
  59: "Gaseosa cola",
  61: "Hamburguesas de carne",
  62: "Harina de maíz",
  63: "Harina de trigo 000",
  64: "Harina de trigo 0000",
  65: "Helado",
  66: "Hipoclorito de sodio",
  68: "Huevos",
  69: "Jabón de glicerina",
  70: "Jabón de tocador",
  71: "Jabón en barra para ropa",
  72: "Jabón en polvo",
  73: "Jamón cocido",
  78: "Lechuga",
  79: "Leonesa",
  82: "Manteca",
  83: "Manzana",
  87: "Margarina",
  88: "Mayonesa",
  90: "Mermelada de durazno",
  94: "Nalga vacuna",
  95: "Naranja",
  96: "Paleta vacuna",
  97: "Pañales",
  98: "Pañales para adultos",
  99: "Pan de molde",
  100: "Pan flauta",
  101: "Papa",
  102: "Papel higiénico",
  103: "Pasta dental",
  104: "Peceto",
  107: "Perfume",
  108: "Pescado fresco",
  110: "Pollo entero",
  112: "Protector solar",
  114: "Pulpa de tomate",
  115: "Queso rallado",
  119: "Repelente en aerosol",
  120: "Repelente en crema o gel",
  122: "Rueda vacuna",
  124: "Sal fina",
  126: "Talco",
  128: "Té negro en saquitos",
  129: "Tinta",
  130: "Toallitas femeninas",
  131: "Tomate",
  134: "Vino tinto",
  135: "Yerba mate",
  136: "Yogur",
  139: "Zapallo",
};
